import {useMemo,useRef,useState} from 'react';
import {warpPixels,type XY} from './retouch-pixels';
export default function WarpEditor({source,onApply}:{source:HTMLCanvasElement;onApply:(canvas:HTMLCanvasElement)=>void}) {
  const initial=()=>Array.from({length:9},(_,i)=>({x:i%3*(source.width-1)/2,y:Math.floor(i/3)*(source.height-1)/2}));
  const [points,setPoints]=useState<XY[]>(initial),drag=useRef<number|null>(null);
  const input=useMemo(()=>source.getContext('2d')!.getImageData(0,0,source.width,source.height),[source]);
  const output=useMemo(()=>{const result=warpPixels(input,points),canvas=document.createElement('canvas');canvas.width=result.width;canvas.height=result.height;canvas.getContext('2d')!.putImageData(new ImageData(result.data,result.width,result.height),0,0);return canvas;},[input,points]);
  return <><p className="muted">Drag the nine handles to bend the patch. Arrow keys move a focused handle; Shift moves faster. Apply rasterizes this layer. Undo restores it.</p><svg className="warp-editor" viewBox={`-8 -8 ${source.width+16} ${source.height+16}`} role="group" aria-label="Warp control grid" onPointerMove={e=>{if(drag.current===null)return;const r=e.currentTarget.getBoundingClientRect();const x=(e.clientX-r.left)/r.width*(source.width+16)-8,y=(e.clientY-r.top)/r.height*(source.height+16)-8;setPoints(p=>p.map((v,i)=>i===drag.current?{x:Math.max(0,Math.min(source.width-1,x)),y:Math.max(0,Math.min(source.height-1,y))}:v));}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
    <image href={output.toDataURL()} width={source.width} height={source.height}/>
    {[0,1,2].flatMap(i=>[<polyline key={`r${i}`} points={points.slice(i*3,i*3+3).map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#00aeef" vectorEffect="non-scaling-stroke"/>,<polyline key={`c${i}`} points={[points[i],points[i+3],points[i+6]].map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#00aeef" vectorEffect="non-scaling-stroke"/>])}
    {points.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={Math.max(source.width,source.height)/65} fill="white" stroke="#0076a8" vectorEffect="non-scaling-stroke" tabIndex={0} role="button" aria-label={`Warp handle ${i+1}`} onPointerDown={e=>{drag.current=i;e.currentTarget.setPointerCapture(e.pointerId);}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const d=e.shiftKey?10:1;setPoints(ps=>ps.map((v,k)=>k===i?{x:Math.max(0,Math.min(source.width-1,v.x+(e.key==='ArrowRight'?d:e.key==='ArrowLeft'?-d:0))),y:Math.max(0,Math.min(source.height-1,v.y+(e.key==='ArrowDown'?d:e.key==='ArrowUp'?-d:0)))}:v));}}/>)}
  </svg><div className="dialog-actions"><button className="secondary" onClick={()=>setPoints(initial())}>Reset grid</button><button className="primary" onClick={()=>onApply(output)}>Apply warp</button></div></>;
}
